# Site settings
title: JEONGMIN CHA's homepage
email: cjm9236@hanyang.ac.kr

description: "This is my homepage - from JEONGMIN CHA"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
highlighter: false
