# Site settings
title: jeongmin.cha @ hanyang-university
email: cjm9236@hanyang.ac.kr

twitter_username: cjm9236
github_username: JeongMinCha
facebook_username: cjm9236

description: "JeongMinCHa - Hanyang University Student"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
#markdown: redcarpet
#redcarpet:
#    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolin", \
#    "strikethrough", "superscript", "with_toc_data", "tables"]
markdown: kramdown

permalink: pretty
highlighter: false

#safe: true
#lsi: true

#gems:
#    - jekyll-redirect-form
#    - jemoji
