# Site settings
title: jeongmin.cha
email: jeongmin.cha@kaist.ac.kr

twitter_username: cjm9236
github_username: JeongMinCha
facebook_username: cjm9236

description: ""
baseurl: ""
url: ""

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# markdown: kramdown

permalink: pretty
highlighter: false

#safe: true
#lsi: true

#gems:
#    - jekyll-redirect-form
#    - jemoji
