# Site settings
title: JEONGMIN CHA's homepage
email: cjm9236@hanyang.ac.kr

twitter_username: cjm9236
github_username: JeongMinCha
facebook_username: cjm9236

description: "This is my homepage - from JEONGMIN CHA"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolin", \
    "strikethrough", "superscript", "with_toc_data", "tables"]

permalink: pretty
highlighter: false
