# Site settings
title: 차정민
email: jeongmin.cha@kaist.ac.kr
github_username: jeongmincha 

description: ""
baseurl: ""
url: ""

# Build settings
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
markdown: kramdown

permalink: pretty
highlighter: false

#safe: true
#lsi: true

#gems:
#    - jekyll-redirect-form
#    - jemoji
